services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3333:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - default

  course-management-systems:
    container_name: course-management-systems
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - default

networks:
  default:
    name: course-management-systems

volumes:
  mysql_data: